title: "Medley Technologies"
description: "Your Technology Development Partner"
images: 
  - "images/hero-image.png"

logo: "arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

location:
  - ""

contact:
  - ""

copyright: "© 2025 Medley Technologies LLC All Rights Reserved"

